FROM node:14.1-alpine

RUN mkdir -p /home/node/app/node_modules
RUN chown -R node:node /home/node/app
WORKDIR /home/node/app

RUN apk add --update python make g++\
   && rm -rf /var/cache/apk/*

# Install app dependencies
COPY package*.json ./
USER node
RUN npm install

COPY --chown=node:node . .

# Running migrations
RUN npm run typeorm -- migration:run

EXPOSE 3000

CMD ["npm", "run", "start:prod"]
